### ISSUE TITLE
Can't install latest version of BeamMP from repository

### ISSUE THREAD

**Issue by mdgkit** [mbentley/docker-beammp-server#1]
Hi, thanks for simple beammp docker image. However, there is one issue.
BeamMP repository changed build naming recently.
From `BeamMP-Server-debian` to
`BeamMP-Server.$DISTRO.$DISTROVERSION.$ARCH`
URL needs to be changed in docker file, or add the build args with file name.

**Comment by mbentley** [comment]
Hey thanks - I missed that they had promoted 3.2.2 to an actual release. I was waiting for the next release before updating since the naming of the artifacts had been changing.  it looks like 3.2.2 was initially released as a pre-release version but then they went back and promoted it to a released version which doesn't send another notification.  It's a bit of a pain to follow due to GitHub not having a notifications for a change in release status.
